### ISSUE TITLE
Doesn't work in firefox

### ISSUE THREAD

**Issue by Dahie** [wizardamigosinstitute/wizardamigosinstitute.github.io#19]
Hi, your site doesn't work in firefox. The video on top is not displayed and no links are working.

Tested with Firefox 49 on OSX 10.11

**Comment by ninabreznik** [comment]
Hey, just tested and seem to work on @serapath computer. Did you type www.wizardamigos.com or the old one wizardamigosinstitute?

**Comment by Dahie** [comment]
The www.wizardamigos.com, however when I visit it now it works. Maybe I had something bad in may cache. 8)

**Comment by ninabreznik** [comment]
Hm, we have to observe, maybe it was something on our side. If you notice some strange behaviour, please let us know :)

**Comment by Dahie** [comment]
Will do :) 👍
